### ISSUE TITLE
Android Errors

### ISSUE THREAD

**Issue by jerninvien** [naoufal/react-native-touch-id#107]
I'm using this package now and find it works very impressively.

Just one minor issue I'd like to mention:

The Android error codes are nowhere near as detailed as the iOS ones. Is there a chance this could be improved at all?

Thanks for your effort on this package!

In this package (which is only Android not dual like yours) they did manage a list of error codes:

[react-native-fingerprint-android](https://github.com/jariz/react-native-fingerprint-android)

**Comment by zibs** [comment]
PR's welcome!
