### ISSUE TITLE
Potential ios 11.3 issue

### ISSUE THREAD

**Issue by dahudson88** [naoufal/react-native-touch-id#111]
Running into a strange scenario that I am unable to find the root cause.  

Enivironment:
react-native-touch-id 4.0.0
react native: 0.50.3

Behavior:
With iPhoneX (ios 11.3):
isSupported() results in biometricType="FaceID"
authenticate() results in App Crash

With iPhone7 (ios 11.3):
isSupported() results in biometricType="TouchID"
authenticate() result in Success

I am chalking this up to something security related with ios update, but wanted to bring it up as an issue.  This does not currently hurt any users that are using my app but may become an issue worth investigating in the future.  Previously with the iPhone X there were no issues using FaceID, when calling authenticate a prompt would open that required the user to allow FaceID permissions.  Now it simply crashes the app.

Below is the code snippet of what I am doing

```

componentWillMount() {
        var that = this;
        //Determine Biometric Type
        TouchID.isSupported()
            .then(biometryType => {
                if (biometryType === 'FaceID') {
                    this.setState({ hasBiometric: true, idType: 'FaceID' })
                } else {
                    this.setState({ hasBiometric: true, idType: 'TouchID' })
                }
            })
            .catch(error => {
                // Failure code
                console.log(error);
            });
}

someLoginFunction()
{
 const optionalConfigObject = {
            title: "Authentication Required",
            color: "#e00606"
        }
        var that = this;
        //If AsyncStorage Data found
      
        if (this.state.hasAsyncStorageData) {

            TouchID.authenticate('Log in', optionalConfigObject)
                .then(success => {
                    alert('I did pass!!!!');
                    that.handleLogin(that.state.asyncStorageEmail, that.state.asyncStoragePassword);
                })
                .catch(error => {
                    alert('Authentication Failed');
                });
        }
}
```

**Comment by DazChong** [comment]
@dahudson88 Adding `NSFaceIDUsageDescription` entry into `Info.plist` will fix the crash.
Although documentation shall highlight this requirement. 

https://stackoverflow.com/questions/46309440/what-is-nsfaceidusagedescription-face-id-usage-description-info-plist-key

**Comment by cpg94** [comment]
Thanks @DazChong !

**Comment by dahudson88** [comment]
Thanks @DazChong I was pretty confused as to what happened as it was working fine before!

**Comment by tomauty** [comment]
Bump as gentle reminder to please add to documentation. Having prod crashes from that.
