### ISSUE TITLE
Call TouchID.authenticate too slow to open dialog

### ISSUE THREAD

**Issue by leonacky** [naoufal/react-native-touch-id#113]
Hi,
I'm using react-native-touch-id, when I call function TouchID.authenticate for show dialog as verify by TouchID, it is working fine on iPhone device, on an android device Xiaomi Redmi 5 Pro but not good on Galaxy Note 8

**Comment by zibs** [comment]
Not sure what we can do about it! Thanks for the heads up though.

Feel free to open a PR if you find a way of improving perf!
