### ISSUE TITLE
Provide a way to close authentication dialogue on Android?

### ISSUE THREAD

**Issue by AbhishekCode** [naoufal/react-native-touch-id#116]
It will be good if we can close authentication dialog from JS in android. iOS its performs well, but on android there are crashes whenever back button is pressed, or app goes in background.

**Comment by dimchez** [comment]
I think crashes are related to #106

**Comment by AbhishekCode** [comment]
Yes you are right

**Comment by zibs** [comment]
Will be making a release this weekend hopefully which fixes crashing

**Comment by svenlombaert** [comment]
@zibs Hi! Any idea when this would be released? Suffering from the same issue now. Package is working excellent in all other cases 👍

**Comment by zibs** [comment]
@svenlombaert 4.0.2 is now on npm - Please open a new issue if you're getting crashes still!

**Comment by AbhishekCode** [comment]
Thanks :)

**Comment by svenlombaert** [comment]
Nice! Only waiting for this one: https://github.com/naoufal/react-native-touch-id/pull/123 to use this package in production
