### ISSUE TITLE
RCTTouchIDUnknownError，Fingerprint verification errors for many times, is locked, how to do

### ISSUE THREAD

**Issue by orzhtml** [naoufal/react-native-touch-id#117]
Fingerprint verification errors for many times, is locked, how to do？

Can't arouse the input device password, unlock the fingerprint?

The fingerprint is locked, what should I do?

**Comment by zibs** [comment]
on iOS if there are too many errors, the OS will require you to re-enter your passcode before it allows touch ID to become available again, systemwide. You'll need to sleep your phone, and re-awaken it using your passcode in order to use Touch ID again.
