### ISSUE TITLE
IOS 11 app crash

### ISSUE THREAD

**Issue by yerevin** [naoufal/react-native-touch-id#119]
Application is crashing when using react-native-touch-id with 
```
react-native: 0.55.4
```
Can somebody look into compatibility this package with newest React native version?

I have in my info.plist	
```
<key>NSFaceIDUsageDescription</key>
<string>Enabling Face ID allows you quick and secure access to your account.</string>
```

**Comment by jaroslav009** [comment]
same issue

**Comment by Nawalnazari** [comment]
any solution guys ?
