### ISSUE TITLE
peerDependencies: react-native: >=0.4.0

### ISSUE THREAD

**Issue by aceminds** [naoufal/react-native-touch-id#12]
npm i --save react-native-touch-id

npm error (npm:2.14.12, node:4.2.4)

With react-native-cli: 0.1.10, the default react-native:0.18.0-rc does not appear to be working. ERR! peerinvalid.

It works when react-native is downgraded to 0.17.0.

**Comment by naoufal** [comment]
@aceminds does removing the react-native peerdependency on this module solve this for you?

**Comment by aceminds** [comment]
Thanks for your prompt reply. Replacing peerDependency  react-native  0.4.0 with 0.18.0-rc worked for me.

**Comment by naoufal** [comment]
I removed `react-native` as a peerDependency all together.  I had done this on my other packages but simply forgot to do it here.  

I published `1.2.4` (with the fix) to npm.  Sorry for the trouble. :+1:
