### ISSUE TITLE
Touch ID error:  react-native-touch-id package

### ISSUE THREAD

**Issue by girishparameswar** [naoufal/react-native-touch-id#121]
I'm creating TouchID sign in on the login page, when the component is loaded, i have to check whether the device supports touchID, When i try to run this code, i will get an error when the component is loaded. Error is: Touch ID Error, and then TouchID is not supported. Can you help me out with this? Appreciate it.

componentDidMount() {
        console.log(Finger);
        Finger.isSupported()
        .then((biometricType)=>{
               console.log(biometricType)
            this.setState({biometricType});
        })
        .catch(error => {
            ToastAndroid.show(`${error} `, ToastAndroid.SHORT);
        })
    }
    render() {
        return(
            <Touchable
                onPress={this.startBiometric}
                activeOpacity={1}>
              <Image
              style={styles.fprint}
              source={require('./image/fingerprint.png')} />
            </Touchable>
        );
    }

    startBiometric() {
        Finger.isSupported()
        .then(authenticate)
        .catch(error => {
            ToastAndroid.show("TouchID not supported", ToastAndroid.LONG);
        });
    }
}

**Comment by zibs** [comment]
Not sure if this is enough for me to go on! If you can post a small reproducible version on github that I can clone and see I'll take a look for you.

**Comment by R10burning** [comment]
@girishparameswar  have u solved it ?
