### ISSUE TITLE
Touch id not working when app comes from background

### ISSUE THREAD

**Issue by muresanandrei** [naoufal/react-native-touch-id#127]
I want when user comes from background to display a lockscreen component with touch id enabled in componentDidMount. For that I use Appstate all is good and touch id prompt shows. But I never get to success part it always fails I get to error as touch alert shows. In console log I get this **"Authentication was canceled by system—for example, if another application came to foreground while the authentication dialog was up."**.
 So I am trying to achieve the same flow as it is on Revolut or Dropbox when you come back to the app from background.

**Comment by worldlee78** [comment]
Any luck with this?

**Comment by Balasnest** [comment]
What is the status?

**Comment by vintage** [comment]
It works for me, but I'm using a bit different solution than `componentDidMount`. I have a top level component `<AppStateManager />` which tracks `AppState` changes. It's mounted once on the app startup, and is never unmounted. When the `change` event on `AppState` occurs a simple conditional is performed to check if current state is `active` and the previous one (stored in component state) been `background` - if so - show the biometrics `TouchID.authenticate`. Works both on iOS and Android.

**Comment by zibs** [comment]
This works on Android, but not on iOS unfortunately

**Comment by kirantripathi** [comment]
@zibs  @vintage  @Balasnest  Did you find any solution for this ?
