### ISSUE TITLE
how to change the words of 'touch sensor' on android  

### ISSUE THREAD

**Issue by nisguptaGit** [naoufal/react-native-touch-id#131]
I wanted to localize 'touch sensor' text.

also want cancel button text must be localize

**Comment by R10burning** [comment]
@nisguptaGit  U can edit it in this xml
node_modules/react-native-touch-id/android/src/main/res/layout/fingerprint_dialog.xml

**Comment by arielrodrigues** [comment]
@nisguptaGit This is possible with the changes made is this PR https://github.com/naoufal/react-native-touch-id/pull/99

**Comment by nisguptaGit** [comment]
@arielrodrigues , PR #99 will work for us.

thanks

**Comment by MrLich** [comment]
how to delete button inputPasscode on iphone ....huhu help me?

**Comment by MrLich** [comment]
have anyone tried to change name of button "cancel" on iphone ? I only change name on android :(( help me.

**Comment by zibs** [comment]
This is now possible in 4.1.0
