### ISSUE TITLE
App crashes on switching apps

### ISSUE THREAD

**Issue by svenlombaert** [naoufal/react-native-touch-id#132]
Hi!

On Android I have this issue, when the fingerprint authentication pop-up is shown. When you switch to another app (using the recent apps button on a Samsung), and then put your finger on the sensor, the app crashes.

 So, apparently it keeps listening when the app has switched. Is there a way to cancel the dialog?

Steps to reproduce:
1. Opening the app and wait till fingerprint screen displays
2. Click on the recent apps button
3. Switch to a different app
4. Click on the home button/fingerprint scanner 
5. The app crashes

**Comment by zibs** [comment]
Released in 4.0.4
