### ISSUE TITLE
Crash on android devices with api level lower than 23

### ISSUE THREAD

**Issue by martinzangl-santexgroup** [naoufal/react-native-touch-id#135]
I've been experimenting with some crashes from devices with API level lower than 23. Works well on hight API level.
`java.lang.NoClassDefFoundError: android.hardware.fingerprint.FingerprintManager$CryptoObject`

I added support libs, and changed **FingerprintManager** to **FingerprintManagerCompat** and works well for older devices.
Thanks

**Comment by martinzangl-santexgroup** [comment]
@guifel no problem

**Comment by zibs** [comment]
We've just released 4.0.3 which should address this - try running it on there - if anyone has issues, please open a new issue, thanks!
