### ISSUE TITLE
Cannot read property 'authenticate' of undefined

### ISSUE THREAD

**Issue by KishPatel1996** [naoufal/react-native-touch-id#14]
Running this snippet of code results in the error in the title, but TouchID.authenticate is a function that is printed to the console.  Not sure what is causing this issue.

```
AsyncStorage.getItem('UserID', (err, result) => {
      console.log(err);
      if (result != null) {
        console.log(TouchID.authenticate);
        console.log(result);
        TouchID.authenticate('Login Process').then(success => {
          console.log('hi');
        }).catch(error => {
          console.log(error);
        });
      }

    });

```

Running this on an iPhone 6 9.3 simulator.

**Comment by naoufal** [comment]
@KishPatel1996 What version of React Native are you running?

**Comment by KishPatel1996** [comment]
@naoufal 0.26.3

**Comment by naoufal** [comment]
I just shipped `2.0.1` to npm.  Can you try with that?  Can you also confirm that you've linked the library?

**Comment by naoufal** [comment]
@KishPatel1996 Going to close this issue.  Let me know if you still have issues after updating and I'll gladly open it again.

**Comment by KishPatel1996** [comment]
Hi @naoufal .  I forgot to link the binary file.

Now, I am running into an error that says TouchID.isSupported is not a function.  I solved this by `var TouchID = require('react-native-touch-id').default`.  Not sure if this was the intention.  If so, I believe it should be reflected in the docs.

Thanks for the great library.

**Comment by Daredevll** [comment]
Having the "Cannot read property 'authenticate' of undefined" with version 3.1.0

**Comment by Taylor123** [comment]
I'm seeing the same thing on version 4.0.1. Looks like NativeModules is not getting imported properly.

 @Daredevll you find a quick fix?

**Comment by skarsad04** [comment]
Currently, if anyone is developing app for both mobile and web, then it is showing error while using TouchID at compile time itself. However TouchID will not work on web.
So, if you create TouchID.web.js and export empty will solve the problem. 
Please  let me know if it is possible to add?
