### ISSUE TITLE
"Try Face ID Again" button is not functional

### ISSUE THREAD

**Issue by MorrisTheHorris** [naoufal/react-native-touch-id#152]
This prompt comes up when the scanner is presented with a non-matching face. I would expect the Try Again prompt to scan again for a face.
- This is react-native-touch-id 4.0.4 / react-native 0.55.4.
- Running on iOS 11.4 iPhone X simulator.

I don't have a physical iPhone X to test this with, but the try again button just doesn't do anything, leaving cancel as the only option when the match fails.
![simulator screen shot - iphone x - 2018-08-29 at 18 02 12](https://user-images.githubusercontent.com/6177164/44774179-c6f25280-abb5-11e8-939f-4447fb33c3e4.png)

**Comment by jemilox** [comment]
I am also seeing this problem...

**Comment by andreialecu** [comment]
Update: this problem doesn't seem to occur on a real physical iPhone X that I tested on.

**Comment by zibs** [comment]
Closing since it sounds like it's working.
