### ISSUE TITLE
iOS: Podspec outdated, pod install breaks project

### ISSUE THREAD

**Issue by andreialecu** [naoufal/react-native-touch-id#157]
https://github.com/naoufal/react-native-touch-id/blob/master/TouchID.podspec

The podspec file depends on `React` which has been deprecated since 2016, and it links to react-native 0.11. Running `pod install` as described in the README then completely breaks projects because of a mismatch between react native versions.

Based on how I see that other projects resolved this, I think the dependency just needs to be removed:

See, for example:
https://github.com/rebeccahughes/react-native-device-info/pull/361/files

**Comment by andreialecu** [comment]
Actually, I think the proper solution is to add:

`pod 'React', :path => '#{node_modules_path}/react-native'` to the root Podfile (in the iOS folder) if it is not already there.

This should be described in the README as it is here for example (in the Cocoapods section):
https://github.com/react-native-community/react-native-linear-gradient

**Comment by zibs** [comment]
@andreialecu can you make a pr??

**Comment by marimarluna** [comment]
i solve deleting this line 
`pod 'React', :path => '#{node_modules_path}/react-native'` 
and add library manually in xcode

**Comment by zibs** [comment]
closing since the PR was always closed.
