### ISSUE TITLE
[Android] No FingerprintAuth in NativeModules

### ISSUE THREAD

**Issue by sanjaymhj** [naoufal/react-native-touch-id#161]
I have some issues in Android only. I am getting `TypeError: Cannot read property 'isSupported' of undefined`. Digging in it seems like FingerprintAuth is undefined in NativeModules.

react-native-touch-id: 4.1.0
RN version: 0.57.0

Please let me know if more information is required.

Thanks

**Comment by zibs** [comment]
Yeah I'm pretty sure this is working as I was testing just the other day. Feel free to make another issue if this is happening.
