### ISSUE TITLE
PasscodeAuth fallback not working

### ISSUE THREAD

**Issue by alberss** [naoufal/react-native-touch-id#172]
I'm using the TouchID/FaceID authentication , and added the new *passcodeFallback* Config to the authenticate method. But I click Enter Passcode button, nothing happens.

This is my Configuration Object:
```
const optionalConfigObject: any = {
      title: 'Authentication Required',
      color: theme.stylesProperties.REGULAR_BLUE,
      fallbackLabel: 'Enter Passcode',
      // fallbackTitle: 'Return to Login',
      passcodeFallback: true
}
```

And here is Authentication performed
```
TouchID.authenticate('Please scan your finger', optionalConfigObject)
      .then((_: any) => {
        // Some actions
      })
      .catch((error: TouchIDError) => {
        this.errorHandler(error)
      })
```

How can I use Passcode fallback? There is extra configuration need it?

**Comment by zibs** [comment]
Yeah we should update the readme, that's not how it's intended to work - it only uses passcode if the device does not have touch id or face ID enabled.

**Comment by alberss** [comment]
Thanks for the clarification, we are using the wrong way

**Comment by alberss** [comment]
I agree, because natively once the TouchID fails, It opens the Passcode Authentication.

**Comment by zibs** [comment]
Feel free to help with a PR if you have time, otherwise I'll try to get to it eventually haha

**Comment by alberss** [comment]
Yes of course! I'll try to do it and send you a PR

**Comment by zibs** [comment]
Great.

**Comment by timothyej** [comment]
@zachrnolan You can hide the "Enter Password" button by setting `fallbackLabel` to an empty string.

I'm also interested in having an "Enter Passcode" option instead.

**Comment by zibs** [comment]
PasscodeFallback only works if the user is not enrolled in touch id/face id.

**Comment by isaaclem** [comment]
@zibs Is there any plan to improve by providing passcodefallback? There are many times the app couldnt detect user's face due to light condition and natively iOS will authenticate using password, I believe user will expect the same behaviour.
