### ISSUE TITLE
FaceID broken on new iOS

### ISSUE THREAD

**Issue by STUkh** [naoufal/react-native-touch-id#173]
Simulator: iOS 12.1 - iPhone X
OS X: 10.14 - Mojave

Biometric available and detected as "FaceID", but after calling ```authenticate``` method - get error: `TouchID Authentication failed TouchIDError: Device does not support Touch ID.`

If switch to iPhone 7 - everything is ok with TouchID.

**Comment by STUkh** [comment]
Probably this line from prev commit break this feature, but i'm not sure:
https://github.com/naoufal/react-native-touch-id/commit/520a60375a0f81e9b141d082883629467dd78a67#diff-7b319858b5c7e6cc6467bc158c09176a

**Comment by zibs** [comment]
Can anyone else verify this? Do you want to make a PR with a fix?

**Comment by STUkh** [comment]
@zibs I've found source of issue. Fortunately it's not related to plugin functionality.
Don't know why, but after upgrade to iOS 12.1 - FaceID access in application settings was disabled.
http://take.ms/YihiP

But i believe it's a sign that we should upgrade "isSupported" method to return error instead of "FaceID" in this case.

**Comment by zibs** [comment]
I see - feel free to open a PR!
