### ISSUE TITLE
How to run without modal

### ISSUE THREAD

**Issue by vaqif14** [naoufal/react-native-touch-id#187]
Please help add with listener and without modal popup

**Comment by GabrielePrestifilippo** [comment]
@vaqif14 I submitted a PR for Android (#194), while it's not possible on iOS

**Comment by zibs** [comment]
I tihnk it's more up to the intent of this repo. On Expo you can now use their unimodules and their LocalAuthentication framework which lets you do this without a dialog.

https://github.com/unimodules/react-native-unimodules
https://docs.expo.io/versions/latest/sdk/local-authentication/
