### ISSUE TITLE
Linking doesn't update MainApplication.java

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [naoufal/react-native-touch-id#188]
I had to manually add these lines to MainApplication.java after linking.

`import com.rnfingerprint.FingerprintAuthPackage;`

and 
`  new FingerprintAuthPackage(),`
(to getPackages())

I had to find out how the package is called by running the example and linking there, because in my project linking is broken. In the example, it works (after some trouble). 

I think it would be better if you also add the manual way to link this project to your app for Android, not just for iOS because linking doesn't work for everyone.

Linking manually on Android is not that hard, just do the above, and:
-  add this to /android/app/build.gradle to the dependencies:
`    compile project(':react-native-touch-id')`
- add this to /android/settings.gradle
`include ':react-native-touch-id'
project(':react-native-touch-id').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-touch-id/android')`

**Comment by ncmd** [comment]
you're a saint.

**Comment by zibs** [comment]
Are you sure? I've just done this on 4.3.0 and 4.4.0. Running `yarn add react-native-touch-id` and then running `react-native link` linked everything fine on my end.

Let me know if this didn't work for you.
