### ISSUE TITLE
Error Application has stopped on Android when build release

### ISSUE THREAD

**Issue by conan52** [naoufal/react-native-touch-id#19]
Hi,
on RN 0.30.0 I have a issue on Android when build release, my application has error "Application has stopped". 

please help me fix it and build new version. Thanks you very much!

**Comment by ng-marcus** [comment]
I have the exact same problem.   In debug it's fine, but in release it crashes on the

import TouchID from 'react-native-touch-id';

08-31 08:37:09.164 11872 11911 E ReactNativeJS: Requiring unknown module "react-native-touch-id".
08-31 08:37:09.203 11872 11911 E ReactNativeJS: Module AppRegistry is not a registered callable module.
08-31 08:37:09.692 11872 11911 E ReactNativeJS: Module AppRegistry is not a registered callable module.

**Comment by ng-marcus** [comment]
My work around is to make a .android.js and a .ios.js version of the file where I used TouchID so the Android version doesn't reference it.

**Comment by laeijebor** [comment]
@ng-marcus ' approach seems best until @richardvanwill 's pull is accepted... close issue?

**Comment by laeijebor** [comment]
Oops missed that richard already marked that pull request as fixing this...
