### ISSUE TITLE
Could not find manifest-merger.jar(react native touch id is on version 4.1.0)

### ISSUE THREAD

**Issue by ronilitman** [naoufal/react-native-touch-id#191]
**Update:** Fix for me was upgrading to version 4.1.1. For now I can't just install latest because of https://github.com/naoufal/react-native-touch-id/issues/171

Since this morning I am getting this error when I'm trying to build my app:
> Could not resolve all artifacts for configuration ':react-native-touch-id:classpath'.
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/manifest-merger/26.0.1/manifest-merger-26.0.1.jar
   > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/26.0.1/ddmlib-26.0.1.jar
   > Could not find dvlib.jar (com.android.tools:dvlib:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/dvlib/26.0.1/dvlib-26.0.1.jar
   > Could not find common.jar (com.android.tools:common:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/common/26.0.1/common-26.0.1.jar
`

I saw that when I'm moving google() upper than jcenter in your build gradle and it does the trick.
In the current version of react native the change was made, but from what I know 4.1.0 is the last stable version, due to: https://github.com/naoufal/react-native-touch-id/issues/171

**Comment by zibs** [comment]
4.4.0 was just released and should solve your problem - please refer to the readme/changelog for the updates!
