### ISSUE TITLE
 How do I translate the error messages ???

### ISSUE THREAD

**Issue by joaodematejr** [naoufal/react-native-touch-id#193]
How do I translate the error messages ??? I am developing an application in portuguese from brazil and the messages are all in english nor in the folder "node_modules" I found the text with the errors.

**Comment by joaodematejr** [comment]
I changed the language of the emulator and the messages translated themselves

**Comment by lincolnbf** [comment]
@joaodematejr All the texts were translated? For me, the text "Not recognized. Try again." still in English, but the others are in portuguese. It happened to you?

**Comment by joaodematejr** [comment]
@lincolnbf  yes, it happened I had to change in the java class inside the folder node_module
