### ISSUE TITLE
Declare touch-id compatibility

### ISSUE THREAD

**Issue by ericvicenti** [naoufal/react-native-touch-id#2]
I notice there is an error for when the device doesn't support touchID. Is there a way to check beforehand if touchID is supported on the device?

```
if (TouchID.isSupported) {
  // this device has a touchID sensor
} else {
  // this is an older device that cannot scan fingerprints
}
```

**Comment by naoufal** [comment]
Hey @ericvicenti thanks for bringing this up.  This is totally doable, we'll just need to factor out [this method](https://github.com/naoufal/react-native-touch-id/blob/master/TouchID.m#L15) and expose it via the library.

I can probably get around to setting that up this weekend.

**Comment by mvayngrib** [comment]
@naoufal you can use [constantsToExport](https://facebook.github.io/react-native/docs/native-modules-ios.html#exporting-constants)
