### ISSUE TITLE
display

### ISSUE THREAD

**Issue by dimlksin2** [naoufal/react-native-touch-id#223]
Hello, may I not use the modal window
Is it possible something like authenticate (false)
creating my fingerprint interface?

**Comment by lincolnbf** [comment]
on iOS i think u cant customizate... android in this project i guess you have to change the library files to modify.

**Comment by zibs** [comment]
Yes you can use Expo's version of this library: If you integrate their unimodules, you can then use  https://github.com/unimodules/react-native-unimodules
https://docs.expo.io/versions/latest/sdk/local-authentication/
