### ISSUE TITLE
It is not supported in RN 0.59

### ISSUE THREAD

**Issue by ligwang** [naoufal/react-native-touch-id#225]
isSupported() return error code "NOT AVAILABLE"

**Comment by zibs** [comment]
Can you post a reproducible example? I'll re-open if you do, thanks!

**Comment by leonardoanalista** [comment]
I ma getting this error: 
`
❌  clang: error: no such file or directory: '/Users/vagrant/Library/Developer/Xcode/DerivedData/[REDACTED]-amqyxfvxotkathehguapaggayebn/Build/Intermediates.noindex/ArchiveIntermediates/Test/BuildProductsPath/Test-iphoneos/libTouchID.a'
`
I am still working to figure out. I'll post here if I fix it.
