### ISSUE TITLE
Any way of removing the "Enter Password" section?

### ISSUE THREAD

**Issue by zibs** [naoufal/react-native-touch-id#23]
I've poked around the code a little bit and can't see where the "Enter Password" fallback message is getting setup. I'm wondering if there is any way to change this string, or remove this section entirely and only have the 'Cancel' option.

Thanks!

**Comment by xwartz** [comment]
Any update news on this?

**Comment by zibs** [comment]
@xwartz I don't think this is possible. If you find out that it is, let me know, and I'll re-open this!

**Comment by lucycliu** [comment]
Editing TouchID.m like this worked for me: https://stackoverflow.com/questions/26635462/ios-touch-id-no-password-button-wanted

**Comment by anagar23** [comment]
set fallbackLabel to empty, will hide "Enter Password".
