### ISSUE TITLE
TouchID Authenticator doesn't always show up

### ISSUE THREAD

**Issue by galimpian** [naoufal/react-native-touch-id#246]
I require on app open that the user needs to authenticate with TouchID/FaceID and or with passcode. The first time I open up the app I am prompted with TouchID authenticator. I swipe up the app out of cache and when I reopen it again I am presented with the passcode screen instead and no TouchID authenticator. I did not fail with the TouchID the first time around so wondering why this behavior is even occurring.
I am also seeing this in the error case when I console log out error but I also see this when the TouchID Authenticator shows too.
`LAErrorSystemCancel | Authentication was canceled by system—for example, if another application came to foreground while the authentication dialog was up.`

**Comment by elirangoshen** [comment]
what you did ? im having this issue as well

**Comment by galimpian** [comment]
@elirangoshen you must change out touchIDDisabled property to true if you want to show FaceID or TouchID

**Comment by elirangoshen** [comment]
from where i change it ? from native ?


> @elirangoshen you must change out touchIDDisabled property to true if you want to show FaceID or TouchID

how ?

**Comment by galimpian** [comment]
@elirangoshen The component itself <PINCode />, if you review the readme doc of all the props it takes you'll see `touchIDDisabled` is one of them and how it works.
