### ISSUE TITLE
TouchID not working on Iphone X and above

### ISSUE THREAD

**Issue by jivanovic** [naoufal/react-native-touch-id#262]
Hello,

when I run my application on an iphone X or above, the function isSupported() returns an error and therefore trying to tell me that TouchID is not supported on this device. 

Although on other iphones it seems to work just fine.

Is anyone else having this issue or maybe knows how to slove it?
Any help would be appreciated :)

**Comment by andrewJA** [comment]
What's about permission? Did you  grant access? FaceID need it unlike TouchID
Also add strings in Info.plist
`<key>NSFaceIDUsageDescription</key>`
  	`<string>To login with FaceID</string>`

**Comment by jivanovic** [comment]
Upps, i fixed it the very same day and forgot to close the issue...My bad 💃 
For anyone who is wondering what stupid thing i forgot,

SOLUTION:
On ipones X and up, the function returns the string "FaceID" and not "TouchID" and ofcourse i forgot to check that option...
