### ISSUE TITLE
"authenticate is not a function"

### ISSUE THREAD

**Issue by ragnorc** [naoufal/react-native-touch-id#28]
This error occurs with React Native 0.41

**Comment by naoufal** [comment]
3.0.0 should fix this.  Let me know if it doesn't and I'll reopen the issue.

**Comment by evanjhopkins** [comment]
I am getting this issue on React Native 0.42 and react-native-touch-id 3.0.0

**Comment by ericcastro92** [comment]
I'm getting this issues on with RN 0.42 and react-native-touch-id 3.0.0 as well.
