### ISSUE TITLE
Missing tags from push

### ISSUE THREAD

**Issue by ThisIsMissEm** [naoufal/react-native-touch-id#29]
Hi! 

Thanks for the release of 3.0.0 and supporting RN 0.40 — I've just noticed though that there's no git tags pushed for 2.0.3, 2.0.4 and 3.0.0; Could you please push them.

Thanks,
Emelia

**Comment by naoufal** [comment]
@ThisIsMissEm Just added them.  Thanks for the reminder! 👋
