### ISSUE TITLE
Not working with React-Native 0.42

### ISSUE THREAD

**Issue by nishant-elivotech** [naoufal/react-native-touch-id#36]
tried iOS and Android..

**Comment by chookg** [comment]
+1

**Comment by basequatro** [comment]
Is this why i'm always getting TouchID not supported?

**Comment by zibs** [comment]
@nishant-elivotech @chookg Are you guys still experiencing this? Can you provide any more information? I know that I've used this library in a wide range of RN versions from 0.40 -> 0.47.1 (current release)

**Comment by kkjdaniel** [comment]
I had some issues getting this to work (using React Native 0.49). Using `import` rather than `require` seemed to solve the issue.

**Comment by zibs** [comment]
Closing - inactive issue for a few months - feel free to re-open if you come across this again.
