### ISSUE TITLE
Improving isSupported on Android

### ISSUE THREAD

**Issue by jjshammas** [naoufal/react-native-touch-id#38]
On the Android version, is there any reason why the `isSupported` method does not return a Promise?

https://github.com/naoufal/react-native-touch-id/blob/master/TouchID.android.js#L9

Returning `Promise.reject()` or something similar would allow the same detection code to be used across both platforms. Currently, I do this:

```
const promise = TouchID.isSupported();
if (!promise) {
  bad();
}
promise.then(() => {
  good();
})
.catch(() => {
  bad();
});
```

I would submit a PR with this idea, but it may be a breaking change for some (though most code written like my example above should interpret the change fine, unless there is a new error code), so wanted to check first if there was a reason behind the current approach.

**Comment by joelcdoyle** [comment]
I think this is the reason for https://github.com/naoufal/react-native-touch-id/issues/33
The README does demonstrate use of `isSupported()` **as if it returns a promise, when in fact it only returns a boolean.**

**Comment by zibs** [comment]
Hey, thanks for reaching out and your consideration.

There will be some initial android support in the coming weeks, so stay-tuned. You're welcome to open your PR, but it might not be necessary if the changes to make Android work will be implementing isSupported() as a promise anyways.
