### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by sarath263** [naoufal/react-native-touch-id#39]
This is by the far, the best touch auth package for RN. Hope it will support android in near future

**Comment by vitconx** [comment]
I found a new library:
https://github.com/hieuvp/react-native-fingerprint-scanner
It probably can help you!

**Comment by zibs** [comment]
I'll be adding some initial (experimental) android support in the coming weeks.

**Comment by sarath263** [comment]
Thank you very much @zibs .  Waiting to implement the same

**Comment by zibs** [comment]
@sarath263 merged into master - release coming this week

**Comment by Mobile-Mike** [comment]
Waiting patiently for a release :)
