### ISSUE TITLE
Is there any way to change the title?

### ISSUE THREAD

**Issue by sergiofraile** [naoufal/react-native-touch-id#43]
The title when prompted for touch id is "Touch ID for (app name)", is there any way to change it?

**Comment by zibs** [comment]
Hi @sergiofraile I don't think this is currently possible, as this is more a platform limitation than this library's. You'll notice if you use Touch ID for other iOS apps that it always says "Touch ID for (app name)". I don't think this is configurable, and is a decision made by Apple (probably to ensure consistency).

You are able to change the `app name`, however. To do this, go into your XCode project and change your app's display name. 

I could be wrong, however, so please let me know if you think this is possible.
