### ISSUE TITLE
Is it possible to give the option to change the title?

### ISSUE THREAD

**Issue by GitHubTracey** [naoufal/react-native-touch-id#47]
Currently, it shows the red fingerprint, and a title of Touch Id for <AppRegistry.registerComponent>
it doesn't match the branding we intend for our app. Is there a way that I can provided a different title?

Thanks!

**Comment by zibs** [comment]
Hi @GitHubTracey does #43 answer your question?

**Comment by GitHubTracey** [comment]
Hi @zibs,  yes, that is what we ended up doing also. I must have not searched the closed issues. My apologies & thanks!
