### ISSUE TITLE
Closing touch-id popup leads to recreating and remounting the view

### ISSUE THREAD

**Issue by dburgmann** [naoufal/react-native-touch-id#49]
After witnessing some weird behavior of animations that were triggered by the response from touch id I figured out, that when ever the touch id prompt is closed (no matter if by successful login or cancel) the view which called the prompt will be recreated and remounted.

This seems like a bug to me as it creates weird behavior because the state of the view is not preserved.

**Comment by naoufal** [comment]
Can you post a code snippet, or better yet, a demo repo for us to reproduce the issue.

**Comment by dburgmann** [comment]
I use this component as TouchIDButton, which is then used in the render() function of my view and gets a login function as prop.

`
export default class TouchIdButton{
  constructor(props) {
    super(props);
  }

  authTouch(){
    return Promise.all([
      TouchID.authenticate(I18n.t('touchIDPromptText')),
      SecureStorage.get('email'),
      SecureStorage.get('password')
    ])
    .then(([success, email, password])=>{
      return this.props.login(email, password)
    })
    .catch((error) => {
    });
  };

  render() {
    return (
      <View style={{alignItems: 'center', marginTop: Global.UNIT * 2}}>
        <TouchableOpacity onPress={()=>{this.authTouch()}}>
          <Icon name="md-finger-print" color="#fff" size={Global.UNIT * 3}/>
        </TouchableOpacity>
      </View>
    );
  }
}
`

**Comment by naoufal** [comment]
Have you inspected componentsWillReceiveProps to see if a prop update is causing the rerender?

**Comment by clavian123** [comment]
@dburgmann did you find the solution for this issue?
