### ISSUE TITLE
Using react-native-touch-id component with landscape mode.

### ISSUE THREAD

**Issue by Skylifee7** [naoufal/react-native-touch-id#50]
Is it possible to show Touch ID authentication pop-up in landscape mode?

**Comment by zibs** [comment]
Hey @Skylifee7 I'm not sure if it is.... according to [This  StackOverflow post](https://stackoverflow.com/questions/26433940/touch-id-prompt-showing-up-as-portrait-in-landscape-only-app)

**Comment by naoufal** [comment]
@zibs is right, it isn't at the moment.
