### ISSUE TITLE
Is this supported on Expo?

### ISSUE THREAD

**Issue by appjitsu** [naoufal/react-native-touch-id#51]
... or does the app have to deployed to the device from xcode?

My code always fails.

"Touch ID is not supported on your device."

```
_loginIDHandler() {
    TouchID.isSupported()
    .then(supported => {
      TouchID.authenticate('Easily login into OTCMe.')
      .then(success => {
        AlertIOS.alert('Authenticated Successfully');
      })
      .catch(error => {
        AlertIOS.alert('Authentication Failed');
      });
    })
    .catch(error => {
      AlertIOS.alert('Touch ID is not supported on your device.');
    });
  }
```

**Comment by naoufal** [comment]
I can speak for Expo, but last I checked the iPhone simulator didn't support TouchID. 

So you have to test on a physical device.

**Comment by zibs** [comment]
@appjitsu Expo supports this out of the box with their own implementation. See the docs here: https://docs.expo.io/versions/latest/sdk/fingerprint.html

@naoufal XCode/iPhone simulator now supports Touch ID! You enable it from Simulator -> Hardware -> Toggle Enrolled State or something, and then you can either fake a successful touch or a failed touch.
