### ISSUE TITLE
Make API surface consistent for android 

### ISSUE THREAD

**Issue by muntact** [naoufal/react-native-touch-id#52]
Hey,

I know that Andorid isn't currently supported but it would be nice if i could call the isSupported function in a consistent manner and expect it to simply say 'No this isn't supported' on android the same way i would expect it to happen on IOS, i.e. return a `Promise` which resolves false.

Currently i have a hack in my node_modules to locally fix this problem: 

```js
/**
 * Stub of TouchID for Android.
 *
 * @providesModule TouchID
 * @flow
 */
'use strict';

export default {
  isSupported() {
    return new Promise((resolve, reject) => {
      resolve(false);
    });
  }
};
```

**Comment by zibs** [comment]
hey @muntact you're definitely not the only person with this concern. I've just made a PR to support android #53 , and the api is now consistent between the platforms.

**Comment by zibs** [comment]
This will be fixed in the latest release - happening sometime this week.
