### ISSUE TITLE
Storing secure data under touch-id

### ISSUE THREAD

**Issue by perry-mitchell** [naoufal/react-native-touch-id#56]
Hi!

I'm sorry to post this here, if it's out of place.. but I've not found any answers that would help me understand what the relationship is with touch ID, this project and authentication.

I would like to store secure information on the device and have it only accessible via touch ID, from this library. This would be ideal if there were some token or key exposed by touch ID authentication, but I haven't found anything in touch-id docs that would elude to such a thing existing.

Is there something I'm missing, or is the intention behind touchID just different?

**Comment by sunto** [comment]
Hi Perry,

For storing secure information what you want to use something like Keychain.  This library is meant for you to easily implement the touch id flow, and to handle a successful authentication via touch id (upon success - access features, retrieve keychain info, etc.)

**Comment by perry-mitchell** [comment]
Thanks @sunto! That's a great answer 👍
