### ISSUE TITLE
Face ID Support for iOS - iPhone X

### ISSUE THREAD

**Issue by ben-snaize** [naoufal/react-native-touch-id#57]
How are you planning to support Face ID?

I've just tested this module (v3.1.0) on an iPhone X and although it does work correctly (so far), it needs some additional detection around Face ID.

Ideally we should be able to present users with the correct wording when opting - for example in our  App we'll show something like 'Use Touch ID?' as an opt-in when logging in (or as a setting switch). If there was additional detection for Face ID e.g. `FaceId.isSupported()` then it presents a simple way for RN to show the user the correct option.

**Comment by naoufal** [comment]
Gee Ben, you're fast!

I'm getting an iPhone X tonight. Will take a look this weekend.

**Comment by ben-snaize** [comment]
Excellent - it was tested in the simulator. I don't have the X yet but we may be getting some in soon.

**Comment by claykohut** [comment]
I'm interested in the same thing!

**Comment by naoufal** [comment]
Just submitted a PR for this.
