### ISSUE TITLE
RCTTouchIDUnknownError - 100% of the time after certain criteria

### ISSUE THREAD

**Issue by ben-snaize** [naoufal/react-native-touch-id#60]
Hi,

I've implemented the following rough structure which fires before allowing access to stored login API credentials.

```
TouchID.isSupported()
        .then(supported => {
        TouchID.authenticate(`${Manifest.name} App credentials for ${username}`)
                  .then(success => {
                          // ... access credentials & login
                  })
                  .catch(err => {
                          // ... don't login
                  })
        })
```

It works just fine until a particular point in production Apps. After which, `authenticate()` gives back `RCTTouchIDUnknownError` 100% of the time. I can happily use `isSupported()` to attempt to prompt the user and re-enable Touch ID, but it still refuses to show the Touch ID dialogue. 

Are there any known issues with this, or any particular reasons why Touch ID would be failing with an 'unknown' error? 

Sorry for any vagueness here but I'm at a point where there's no further info available to me. The application's state is correct as I would expect the Touch ID call to fire at this point, but the error is thrown instead.

**Comment by Shinichi52** [comment]
i has same issue :(

**Comment by zibs** [comment]
@Shinichi52 @ben-snaize If a user has failed to authenticate 3+ times with their Touch ID, iOS will disable Touch ID until the user has entered their passcode in again from the lock screen to re-enable touch ID. 

Do you think that this could be what's happening?

**Comment by Shinichi52** [comment]
@zibs no, I don't thing so. I have show passcode when Touch ID isn't support (i'm using https://github.com/naoufal/react-native-passcode-auth for passcode). But It works just fine until a particular point in production Apps. After which, authenticate() gives back RCTTouchIDUnknownError 100% of the time.

**Comment by davidgruebl** [comment]
I started experiencing the very same issue recently. However I've not yet understood what the clear pattern is here.

**Comment by ben-snaize** [comment]
Any update on this @naoufal?

**Comment by naoufal** [comment]
@ben-snaize Happy to take a look if you can provide a reproducible example.

**Comment by davidgruebl** [comment]
Based on the changes I made in this pr https://github.com/naoufal/react-native-touch-id/pull/78/files I figured that the error causing this behaviour is `LAErrorNotInteractive` 

I'm not sure what is causing this error on the native layer, also there doesn't seem to be munch information around this error code.

**Comment by ben-snaize** [comment]
@nisguptaGit @naoufal @davidgruebl Would be great to have these new errors included as it will help to debug this issue. I'm currently holding off releasing the feature to our Apps as I can't resolve it currently.

**Comment by Shinichi52** [comment]
@ben-snaize i resolved my issue after changed to https://github.com/tradle/react-native-local-auth. it's working fine.

**Comment by zibs** [comment]
I'm not sure if this still an issue or not, so closing unless otherwise!

**Comment by tegozen** [comment]
after a few failed attempts, the iphone prompts you to enter your password. this affects touchid entirely. even when unlocking the phone, he could not determine the fingerprint until I entered the password. I'm not sure if this is your problem, but the symptoms are similar.
