### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by minotaurrr** [naoufal/react-native-touch-id#61]
Hi guys,

I keep getting this message - undefined is not an object (evaluating 'NativeTouchID.isSupported')
undefined is not an object (evaluating 'NativeTouchID.authenticate')

did react-native link many times
tried rm -rf ./node_modules && npm install && react-native link

this is my code

```
import React, { Component } from 'react';
import { View, Text, TouchableHighlight, Alert } from 'react-native';
import TouchID from "react-native-touch-id";

export default class Authentication extends Component {
    componentDidMount() {
        TouchID.isSupported()
            .then(supported => {
                console.log('it is supported');
            })
            .catch(err => {
                console.log(err.message);
            })
    }
    authHandler() {
        TouchID.authenticate('to demo this component')
            .then(success => {
                console.log(success);
                Alert.alert('auth successed');
            })
            .catch(err => {
                Alert.alert(err.message);
            })
    }
    render() {
        return (
            <View style={ styles.container }>
              <TouchableHighlight onPress={ this.authHandler }>
                <Text>
                  Authenticate with Touch id
                </Text>
              </TouchableHighlight>
            </View>
        )
    }
}

const styles = {
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    }
}
```

**Comment by jzhw0130** [comment]
Same issue.  on Samsung S6, Android 7.0

**Comment by jzhw0130** [comment]
/**
 * Stub of TouchID for Android.
 *
 * @providesModule TouchID
 * @flow
 */
'use strict';

export default {
  isSupported() {
    return false;
  }
};

Wrong code for Android. Please update as:

  isSupported() {
    return new Promise((resolve, reject) => {
        resolve(false);
    });
  },

**Comment by zibs** [comment]
This fix has now been merged into master and will be released in the next release.

**Comment by kkarmalkar** [comment]
I am getting `undefined is not an object (evaluating 'NativeTouchID.isSupported')` for above code on iPhone. Please let us know in which version is fixed and when it is available to download??

**Comment by ShortyFR** [comment]
Getting the same Error on Android (OnePlus5) using version 4.0.0

**Comment by morgan-legal** [comment]
Same issue on iOS with version `4.0.0`

**Comment by Taylor123** [comment]
Has anyone found a fix for this? It seems to be a recurring issue https://github.com/naoufal/react-native-touch-id/issues/14 

version: 4.0.1

**Comment by prigoose** [comment]
Having the same issue on a OnePlus 6t

**Comment by pke** [comment]
This is still happening on devices without any support for such capabilities (old Android).

https://github.com/naoufal/react-native-touch-id/blob/master/TouchID.android.js#L7

seems to return no promise, but undefined if `isSupported(config)` yields undefined.
