### ISSUE TITLE
Android native bridge broken

### ISSUE THREAD

**Issue by Knight704** [naoufal/react-native-touch-id#62]
Commands:
```yarn add react-native-touch-id```
```react-native link react-native-touch-id```

In output to second command there are no android linking info, also there is no android folder under node_modules/react-native-touch-id and therefore no changes in native android files.

react-native-touch-id v3.1.0

**Comment by zibs** [comment]
hey @Knight704 

I think the Readme is out of date until the new release is out. At this moment Android support has been merged to masted, but hasn't been released on npm.

**Comment by Mobile-Mike** [comment]
Can someone share their Android build.gradle and MainApplication.java for this project as react native link for Android does not link it at all, ios fine.
Cheers

**Comment by MasterDaveh** [comment]
To have Android support:
1. Replace your package.json declaration with `"react-native-touch-id": "https://github.com/naoufal/react-native-touch-id.git"` to have npm fetch the github package
2. `npm install` or `yarn install` to fetch the correct package
3. `react-native link react-native-touch-id` to link correctly the Android version as well

**Comment by Mobile-Mike** [comment]
Cheers @MasterDaveh

**Comment by naoufal** [comment]
@zibs @MasterDaveh thanks for chiming in and helping out.  

Just published 4.0.0 to npm with support for Android 🚀 

@Mobile-Mike you should be able to point back to `react-native-touch-id` now.
