### ISSUE TITLE
Android TouchId add more attempts

### ISSUE THREAD

**Issue by bhd-vasyl** [naoufal/react-native-touch-id#63]
It seems that on android user has only one attempt to match fingerprint.
Is there any possibilities to increase attempt count?

**Comment by renanpupin** [comment]
Same problem here.

**Comment by zibs** [comment]
I don't think this is something we would implement internally, rather would leave it up the developer to do something like #67 (once it's fixed!) where you would loop through and re-open the dialog if it wasn't successful.
