### ISSUE TITLE
Npm installs old codebase differs from master branch

### ISSUE THREAD

**Issue by alex-stepchenkov-neyber** [naoufal/react-native-touch-id#64]
Please, update version and tag codebase, because npm installs some old codebase. You can see actual install result in tag branch 3.1.0

**Comment by Stanok3694** [comment]
Hi!
Could you please update npm package? I cannot use FaceId functionality of your tool...:(
Thank you!

**Comment by edcrampin** [comment]
As a temporary workaround, you can directly link to the GitHub codebase from within NPM until the NPM codebase has been updated.

An example of how to do this below:

https://github.com/naoufal/react-native-touch-id/issues/62#issuecomment-355036866

**Comment by naoufal** [comment]
@alex-stepchenkov-neyber, @Stanok3694, @edcrampin Just published 4.0.0 to npm.  Sorry for the delay folks.
