### ISSUE TITLE
Android FingerprintManager not supported for API lower than 23

### ISSUE THREAD

**Issue by MasterDaveh** [naoufal/react-native-touch-id#65]
I was testing the module on a couple of devices with respectively API level 21 and 17. 
With both of the devices I could manage to install the signed release APK but the app would just crash saying "the app has stopped". 
From the Logcat in Android Studio I managed to get a stacktrace with a `java.lang.RuntimeException: Could not invoke FingerprintAuth.isSupported` error. 
I then bumped into [this](https://stackoverflow.com/a/45182594/4811744) SO answer which states that "FingerprintManager is supported in API 23 and Higher", which is confirmed [here](https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager.html).

The same APK is working on a Nexus 5X with Android version 8, so API level should be 26.

Are there any known workarounds at the moment?

**Comment by szczepcio95** [comment]
Any ideas? Having the same problem

**Comment by szczepcio95** [comment]
Okey, I've got something. Just before authenticating try this
```
if (Platform.OS === 'android' && Platform.Version <= 23 ) {
            // not performing any TouchID actions
        }
```

**Comment by marcorm** [comment]
Does this [PR](https://github.com/naoufal/react-native-touch-id/pull/70) resolve this issue?

**Comment by marcorm** [comment]
I think, in 
> FingerprintAuthModule.java

this:
```
  public void isSupported(Callback reactErrorCallback, Callback reactSuccessCallback) {
    keyguardManager = (KeyguardManager) getCurrentActivity().getSystemService(Context.KEYGUARD_SERVICE);
    fingerprintManager = (FingerprintManager) getCurrentActivity().getSystemService(Context.FINGERPRINT_SERVICE);
    if(!isFingerprintAuthAvailable()) {
      reactErrorCallback.invoke("Not supported.");
    } else {
      reactSuccessCallback.invoke("Is supported.");
    }
    return ;
  }
```
should become something like:
```
  public void isSupported(Callback reactErrorCallback, Callback reactSuccessCallback) {
    if(!isFingerprintAuthAvailable()) {
      reactErrorCallback.invoke("Not supported.");
    } else {
      keyguardManager = (KeyguardManager) getCurrentActivity().getSystemService(Context.KEYGUARD_SERVICE);
      fingerprintManager = (FingerprintManager) getCurrentActivity().getSystemService(Context.FINGERPRINT_SERVICE);
      reactSuccessCallback.invoke("Is supported.");
    }
    return ;
  }
```
Correct me if i'm wrong...

**Comment by gazaret** [comment]
Fixed in #96

**Comment by marcorm** [comment]
Hi @gazaret , are you sure your solution work? Because the solution i proposed is unstable...

**Comment by gazaret** [comment]
Hi @marcorm , yes it was unstable on api 23+.
Now fixed this.
Tested on android 4.4 and 7.0. It works.

**Comment by zibs** [comment]
We now have some handling for this in 4.0.3 - please give it a shot and let us know by opening a new issue if the problem persists.
