### ISSUE TITLE
Android crashes when authentication fails at second time

### ISSUE THREAD

**Issue by renanpupin** [naoufal/react-native-touch-id#67]
It seems that android still keep the Fingerprint working after the first authentication.

`
ERROR: RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
`

TEST: Loop until authentication() returns true, at the second time this will crash.

```js
async validateTouchId(){
        let isAuthOk = false;
        while(!isAuthOk){

            try{
                let responseAuth = await TouchID.authenticate('Authentication');

                if(responseAuth){
                    isAuthOk = true;
                    return true;
                }else{
                    throw responseAuth;
                }

            } catch (e){
                console.log("Error",e);

                let successPromise = await new Promise((resolve, reject) => {
                    Alert.alert(
                        'Auth',
                        "Auth again.",
                        [
                            {text: 'Login again', onPress: () => {
                                    resolve(false);
                                }},
                            {text: 'Try again', onPress: async () => {
                                    resolve(true);
                                }},
                        ]
                    );
                });

                if(!successPromise){
                    return false;
                }
            }
        }
    }
```

**Comment by agustinaliagac** [comment]
Same here ! Reproducing this bug on physical devices and emulators as well.

**Comment by agustinaliagac** [comment]
It looks like the native Callback implementation only allows invoking it once: 
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/CallbackImpl.java

**Comment by zibs** [comment]
Thanks for reporting this issue!

I can take a look in the coming days/weeks for a workaround - in the meantime feel free to open a PR if this is breaking for you!

**Comment by indieocean** [comment]
Yeah we fixed this issue using promises since there is a mix of callbacks and promises it falls into the multiple callback issue. While using promises you don't have this issue since you don't send any more callback to native.

**Comment by marcorm** [comment]
Hi @indieocean , could you please share what you've done? Thanks a lot!

**Comment by zibs** [comment]
Master has a fix for this now, but is not yet released. will be bumped soon

**Comment by MikhailSemichev** [comment]
Guys, could anyone consult when npm release with this bug fix will be shipped? Current release version is 4.0.0 and we are waiting for 4.x.x with the fixes. Thanks in advance.

**Comment by zibs** [comment]
Yep any day now.

**Comment by ycb0318** [comment]
I also have this problem yet，Did not solve it?

**Comment by zibs** [comment]
@ycb0318 This has been out for a while in 4.0.1+

**Comment by johakr** [comment]
@naoufal Please reopen this issue since it's still happening in 4.0.4 on android.

**Comment by zibs** [comment]
@johakr Can you post any more details about what's happening for you. I can't reproduce on latest.

**Comment by johakr** [comment]
@zibs 

`java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
    at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:28)
    at com.rnfingerprint.DialogResultHandler.onError(DialogResultHandler.java:22)
    at com.rnfingerprint.FingerprintDialog.onError(FingerprintDialog.java:147)
    at com.rnfingerprint.FingerprintHandler.onAuthenticationFailed(FingerprintHandler.java:43)
    at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedFailed(FingerprintManager.java:1320)
    at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:1227)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`
