### ISSUE TITLE
Use this and Facebook login

### ISSUE THREAD

**Issue by kevinzzz007** [naoufal/react-native-touch-id#7]
Hi, thank you so much for building this, it looks so COOL!  I want to use it for my app, which uses Facebook login, was wondering if I want to integrate the two, how should I approach this?

Again, thank you so much!

**Comment by naoufal** [comment]
Hi @kevinzzz007,

Well it really depends on you.  But you could have the user log in with FB the first time he opens the app and have subsequent logins use Touch ID.

**Comment by naoufal** [comment]
If you're not already, you should use https://github.com/facebook/react-native-fbsdk for your Facebook login. :smile:

**Comment by naoufal** [comment]
Closing this issue, since it's more of a question than an issue with the module itself.
