### ISSUE TITLE
Unification of error messages across platforms

### ISSUE THREAD

**Issue by rodan-lewarx** [naoufal/react-native-touch-id#76]
have you thought about unification of error messages across platforms?

Curently there are documented iOS errors, these have proper names, messages and details. But errors on Android are entirely different - all returns Touch ID Error and error message is in details instead of message, etc.

Wouldnt it be better if this library would throw own errors instead that would be the same across platforms?

**Comment by naoufal** [comment]
Would totally accept a PR including this change!

You up for it?

**Comment by rodan-lewarx** [comment]
@naoufal Well I am not much of iOS or Android developer but I can try. Do you have some preferences or thoughts about the way this should be implemented?

**Comment by zibs** [comment]
This is now possible in 4.1.0
