### ISSUE TITLE
Unable to resolve module invariant

### ISSUE THREAD

**Issue by jrans** [naoufal/react-native-touch-id#8]
[here](https://github.com/naoufal/react-native-touch-id/blob/master/TouchID.ios.js) requires invariant to be installed globally, so either add to package.json or remove if not needed..

**Comment by naoufal** [comment]
Thanks for the issue. @jrans.  

If you have some time would you like to submit a PR for removing the require statement?

**Comment by naoufal** [comment]
Resolved by https://github.com/naoufal/react-native-touch-id/commit/5a5e40ec5b0b105203891c9574ac6bab8c25fc20
