### ISSUE TITLE
Can i get any unique key to recognize user identity?

### ISSUE THREAD

**Issue by wayne215** [naoufal/react-native-touch-id#82]
As caption. Something like the touch id hash. 
Because i want to send it with ID to server to get the token back. Thanks all.

**Comment by olivierdelomez** [comment]
I'm not sure there's something like touchID hash. If you want to send something to your server with a successful touchID you can use something like json web tokens.

**Comment by zibs** [comment]
I don't think iOS/Android offers anything natively here for you, sorry! You'll have to come up with something of your own.
