### ISSUE TITLE
Property 'biometryType' not found on object of type 'LAContext

### ISSUE THREAD

**Issue by olivierdelomez** [naoufal/react-native-touch-id#86]
Hello,

While trying to install this lib (4.0.0) I ran into the following error:

`error: property 'biometryType' not found on object of type 'LAContext *'
        return context.biometryType == LABiometryTypeFaceID ? @"FaceID" : @"TouchID"`
`error: use of undeclared identifier 'LABiometryTypeFaceID'
        return context.biometryType == LABiometryTypeFaceID ? @"FaceID" : @"TouchID";

I also tried with a fresh React Native install (react-native init), I did linked the libraries & the npm install run fine. The errors are returned when I run `react-native run-ios`

3.1.0 package work as intended

Any idea why ?

**Comment by RodrigoAngeloValentini** [comment]
Hi!
I am having the same problem. Did you find any solution?

**Comment by olivierdelomez** [comment]
alas no, I downgraded to 3.1.0

**Comment by RodrigoAngeloValentini** [comment]
I updated the XCode to version 9 and the problem was solved

**Comment by olivierdelomez** [comment]
Okay, I'm updating XCode (9.2)

**Comment by olivierdelomez** [comment]
I'm closing it, updating XCode fixed my issue
