### ISSUE TITLE
undefined is not an object (evaluating 'NativeTouchID.isSupported')

### ISSUE THREAD

**Issue by kkarmalkar** [naoufal/react-native-touch-id#89]
I am getting **undefined is not an object (evaluating 'NativeTouchID.isSupported')** for sample code of Touch ID on iPhone. Please let us know in which version it is fixed and when it will available to download??

**Comment by zibs** [comment]
It sounds like you may not have properly linked the library, or you are just copy/pasting the sample code without importing something properly!

Please provide a code sample, the version of the library you are using

Thanks

**Comment by SkrewEverything** [comment]
@kkarmalkar I'm facing similar problem. How did you solve it?

I ran `react-native link` but still I'm getting similar error.

**Comment by sritharIOS** [comment]
I am also getting the same issue but resolved after using the "pod install"
