### ISSUE TITLE
touchID breaks Cmd+R in simulator

### ISSUE THREAD

**Issue by pgmemk** [naoufal/react-native-touch-id#9]
I am very grateful to you for this component. It is extremely important for our app. 

The problem is that in the simulator, after successful authentication, Cmd+R stops working. Strangely, if you call TouchID.authenticate() again and cancel it, it starts working again.

**Comment by naoufal** [comment]
Hey @pgmemk,

That's very odd.  Do you have any leads as to what may be causing this?

**Comment by pgmemk** [comment]
Hey, I don't have a problem with it any more. Found some work around such as if after authentication you press Cmd+R and it does not work you can press Cmd+Options+M and after that Cmd+R works :)

**Comment by naoufal** [comment]
Glad you found a fix.
