### ISSUE TITLE
Android String constant to be configurable?

### ISSUE THREAD

**Issue by hkung77** [naoufal/react-native-touch-id#95]
Anyway we can add to the config object for this string? 

https://github.com/naoufal/react-native-touch-id/blob/master/android/src/main/res/layout/fingerprint_dialog.xml#L49

I'm working with several languages other and was hoping this is something that could be included.

Thanks

**Comment by zibs** [comment]
@hkung77 that's a good point - we should probably consider adding I18n to all aspects of the library. feel free to open a PR!

**Comment by zibs** [comment]
PR open for #99 will resolve this.
