### ISSUE TITLE
[Android] Crash when no config is specified

### ISSUE THREAD

**Issue by Aidurber** [naoufal/react-native-touch-id#98]
Hello!

I've just been scratching my head for a while, I got the TouchID and FaceID working for iOS and began to test the implementation on Android. 

After reading Logcat I noticed the following error: 
> unknown:React: com.facebook.react.bridge.NoSuchKeyException: couldn't find key title in dynamic object

This was because I didn't provide the "optional" config on Android :grin:

Might be prudent to specify that it's mandatory in the docs, or do some defensive checks in `FingerprintDialog.java` and/or provide some defaults, the issue lines were here: 
```java
        getDialog().setTitle(authConfig.getString("title"));
        int color = authConfig.getInt("color");
```

Posting to hopefully save someone else some time. 

P.S. Thank you for this library, I was dreading implementing TouchID support. You've saved me a bunch of time, I really appreciate it. :heart:

**Comment by ycb0318** [comment]
+1

**Comment by Aidurber** [comment]
I may be able to create a PR with a fix if I have time.

**Comment by zibs** [comment]
Yeah, the crash is happening since you're probably passing in an empty object still. If there is an empty config, passed in, it still thinks there is a config there, so it'll fail. This could easily be remedied in a PR! or I could get to it later this week.

**Comment by ycb0318** [comment]
thank you!




发自网易邮箱大师


在2018年03月7日 17:43，Andrew Durber<notifications@github.com> 写道：

I may be able to create a PR with a fix if I have time.

**Comment by zibs** [comment]
merged and will be released!
